akTeams/urls.py
from django.urls import path

from . import views



# map urls with views
urlpatterns = [
    # Team
    path('', views.index, name='team.index'),
    path('create', views.create, name='team.create'),
    path('update/<int:id>', views.update, name='team.update'),
    path('delete/<int:id>', views.delete, name='team.delete'),
    path('affectation/<int:id>', views.affectation, name='team.affectation'),



]

employee_leave_management/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('leave/', include('leaveManagmentItazouti.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('register/<id>', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name= 'users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('change_password/', user_views.change_password, name='change_password'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leaveRequests/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'LEAVE'
urlpatterns = [
    path('', views.index_leave, name='index_leave'),
    path('requestList', views.request_list, name='request_list'),
    path('employers_requests/<id>', views.employers_requests, name='employers_requests'),
    path('cancel_request/<id>', views.cancel_request, name='cancel_request'),
    path('update_request/<id>', views.update_request, name='update_request'),
    path('show_notification_manager/<id>', views.show_notification_manager, name='show_notification_manager'),
    path('update_employer_request/<id>', views.update_employer_request, name='update_employer_request'),
    path('delete_employer_request/<id>', views.delete_employer_request, name='delete_employer_request')

]

yh_be/urls.py
from django.urls import path
from . import views

# map urls with views
urlpatterns = [
    path('', views.index, name='be.index'),
    path('<int:id>', views.show, name='be.show'),
    path('create', views.create, name='be.create'),
    path('update/<int:id>', views.update, name='be.update'),
    path('delete/<int:id>', views.delete, name='be.delete'),
]

leaveRequests/models.py
from django.db import models
from settingEmployer.models import Employee
from django.utils import timezone
import datetime

# Create your models here.

STATUS = (('ACCEPTED', 'accepted'),
          ('REJECTED', 'rejected'),
          ('WAITING', 'waiting'),
          ('CANCELED', 'canceled')
          )
MOTIF = (('Sick Day', 'Sick Day'),
         ('Unpaid', 'Unpaid'),
         ('Recovery', 'Recovery'),
         ('Vacation', 'Vacation'),
         ('Parental Leave', 'Parental Leave')
         )


class LeaveRequest(models.Model):
    leave_request_code = models.CharField(max_length=10, null=True, blank=True, unique=True)
    start_date = models.DateField(default=timezone.now)
    start_time = models.TimeField(default=datetime.time(8, 00, 00))
    end_date = models.DateField(default=timezone.now)
    end_time = models.TimeField(default=datetime.time(17, 00, 00))
    create_date = models.DateTimeField(default=timezone.now, blank=True)
    status = models.CharField(choices=STATUS, null=True, blank=True, max_length=50)
    motif = models.CharField(choices=MOTIF, null=True, blank=True, max_length=50)
    reason = models.TextField(max_length=200, null=True, blank=True)
    employee = models.ForeignKey(Employee, related_name='Employee', on_delete=models.SET_NULL, blank=True, null=True)
    manager = models.ForeignKey(Employee, related_name='Manager', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.leave_request_code


class Notifications(models.Model):
    title = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(Employee, related_name='Created_By', on_delete=models.SET_NULL, blank=True,
                                   null=True)
    created_to = models.ForeignKey(Employee, related_name='Created_To', on_delete=models.SET_NULL, blank=True,
                                   null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    tag_vu = models.BooleanField(default=False)
    leave_request = models.ForeignKey(LeaveRequest, related_name='Leave_Request', on_delete=models.SET_NULL, blank=True,
                                   null=True)

    def __str__(self):
        return self.title

akTeams/form/forms.py
from django import forms
from leaveManagementApp.models import Team

class TeamForm(forms.ModelForm):

    class Meta:
        model = Team

        fields = [
            'team_code',
            'libelle',
            'members'


        ]

    def __init__(self, *args, **kwargs):
            super(TeamForm, self).__init__(*args, **kwargs)

            for visible in self.fields:
                self.fields[visible].widget.attrs.update({'class': 'form-control'})

leaveRequests/forms.py
from django import forms
from .models import LeaveRequest,Notifications


class LeaveRequestForm(forms.ModelForm):
    class Meta:
        model = LeaveRequest
        fields = [
            'leave_request_code',
            'start_date',
            'start_time',
            'end_date',
            'end_time',
            'create_date',
            'status',
            'motif',
            'reason',
            'employee',
            'manager'
        ]

    def __init__(self, *args, **kwargs):
        super(LeaveRequestForm, self).__init__(*args, **kwargs)
        self.fields['reason'].widget.attrs.update({"style": "height: 120px;"})
        self.fields['motif'].widget.attrs.update({"style": "margin-top: 20px;"})
        for visible in self.fields:
            self.fields[visible].widget.attrs.update({'class': 'input--style-4'})

akTeams/views.py
from django.shortcuts import render,get_object_or_404,redirect
from leaveManagementApp.models import Team
from .form.forms import TeamForm
from akTeams.form.membreTeamForms import MemberTeamForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from akTeams.decorators import role_requiredadmin
# Create your views here.

@login_required
@role_requiredadmin()
def index(request):
    # form = TeamForm(request.POST or None)
    list_teams = Team.objects.all()
    context = {
        'list_teams': list_teams,
    }
    return render(request, 'team/index.html', context)


@login_required
@role_requiredadmin()
def create(request):
    form = TeamForm(request.POST or None)
    if form.is_valid():
        form.save()
        # messages.info(request, 'Team created')
        return redirect('team.index')

    context = {
        'form': form,
        'modeCreate': True
    }

    return render(request, 'team/ajoutTeam.html', context)
@login_required
@role_requiredadmin()
def update(request, id):

    item = get_object_or_404(Team, pk=id)
    form = TeamForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('team.index')


    context = {
        'form': form,
        'modeCreate': False
    }
    return render(request, 'team/ajoutTeam.html', context)
@login_required
@role_requiredadmin()
def delete(request, id):

        item = get_object_or_404(Team, pk=id)
        item.delete()
        return redirect('team.index')

@login_required
@role_requiredadmin()
def affectation(request, id):

    item = get_object_or_404(Team, pk=id)

    form = MemberTeamForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('team.index')


    context = {
        'form': form,
        'teamSelected':item

    }
    return render(request, 'membreTeam/affectation.html', context)

leaveRequests/views.py
import self as self
from django.shortcuts import render, redirect
from .forms import LeaveRequestForm
from .models import Employee, LeaveRequest, Notifications
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def send_notification(created_by, created_to, title, id_leaveRequest):
    leave_request = LeaveRequest.objects.get(pk=id_leaveRequest)
    # add new notification
    notification = Notifications.objects.create(
        title=title,
        created_by=created_by,
        created_to=created_to,
        leave_request=leave_request
    )
    notification.save()
    return notification


@login_required
def index_leave(request):
    if request.method == 'POST':
        user = request.user
        employer = Employee.objects.get(user_id=user.id)
        form = LeaveRequestForm(request.POST or None)
        manager = Employee.objects.get(id=employer.manager_id)
        if form.is_valid():
            leave_request = form.save(commit=False)
            leave_request.employee = employer
            leave_request.manager = manager
            leave_request.status = "waiting"
            leave_request.save()
            # add new notification
            title = employer.first_name + ' ' + manager.last_name + ' sent you an new leave request'
            send_notification(employer, manager, title, leave_request.id)
            messages.success(request, 'You have sent the leave request to your manager successfully !!')
            return redirect('/leave/requestList')
        else:
            print('test:', form.errors)

    else:
        form = LeaveRequestForm()

    context = {
        'form': form
    }
    return render(request, 'requests/leavesRequest.html', context)


@login_required
def request_list(request):
    user = request.user
    employer = Employee.objects.get(user_id=user.id)
    requests_list = []
    options = LeaveRequest.objects.all()
    try:
        for r in options:
            if r.employee_id == employer.id:
                requests_list.append(r)
            else:
                print('err')
    except:
        requests_list = []

    context = {
        'requests_list': requests_list,
        'employer': employer
    }
    print()
    return render(request, 'requests/requestsList.html', context)


@login_required
def cancel_request(request, id):
    try:
        leave_request = LeaveRequest.objects.get(pk=id)
        leave_request.status = "canceled"
        leave_request.save()
        messages.success(request, 'You have canceled the leave request to your manager successfully !!')
        return redirect('/leave/requestList')

    except:
        msg = "can you try again"
        print(msg)

    return redirect('/leave/requestList')


@login_required
def update_request(request, id):
    leave_request = LeaveRequest.objects.get(pk=id)
    status = leave_request.status
    employer = leave_request.employee
    manager = leave_request.manager
    form = LeaveRequestForm(request.POST or None, instance=leave_request)
    if form.is_valid():
        leaveRequest = form.save(commit=False)
        leaveRequest.status = status
        leaveRequest.employee = employer
        leaveRequest.manager = manager
        leaveRequest.save()
        messages.success(request, 'You have canceled the leave request to your manager successfully !!')
        return redirect('/leave/requestList')
    context = {
        'form': form
    }
    return render(request, 'requests/editRequest.html', context)


def get_user_notifications(request):
    user = request.user
    new_notifications = []
    try:
        employer_user = Employee.objects.get(user_id=user.id)
        for n in Notifications.objects.all():
            if n.created_to_id == employer_user.id and n.tag_vu is False:
                new_notifications.append(n)
        count = len(new_notifications)
        if count == 0:
            context = {
                'notifications': new_notifications
            }
        else:
            context = {
                'notifications': new_notifications,
                'count': count
            }
        return context
    except:
        context = {
            'notifications': []
        }
        print('test')
        return context


def accept_refuse(id, choice):
    leave_request = LeaveRequest.objects.get(pk=id)
    leave_request.status = choice
    leave_request.save()
    return leave_request.status


@login_required
def show_notification_manager(request, id):
    user = request.user
    employee = Employee.objects.get(user_id=user.id)
    id_user = str(employee.id)
    try:
        # notification
        notification = Notifications.objects.get(pk=id)
        notification.tag_vu = True
        notification.save()
        # employer
        employer = Employee.objects.get(pk=notification.created_by_id)
        # leave request
        leave_request = LeaveRequest.objects.get(pk=notification.leave_request_id)
        form = LeaveRequestForm(request.POST or None)
        if request.method == 'POST' and 'refuse' in request.POST:
            accept_refuse(leave_request.id, 'rejected')
            title = 'Your manager ' + employee.first_name + ' ' + employer.last_name + ' refuse your leave request'
            send_notification(employee, employer, title, leave_request.id)
            return redirect('/leave/employers_requests/' + id_user)
        if request.method == 'POST' and 'accept' in request.POST:
            accept_refuse(leave_request.id, 'accepted')
            title = 'Your manager ' + employee.first_name + ' ' + employer.last_name + ' accept your leave request'
            send_notification(employee, employer, title, leave_request.id)
            return redirect('/leave/employers_requests/' + id_user)
        context = {
            'employer': employer,
            'leave_request': LeaveRequest.objects.get(pk=notification.leave_request_id),
            'profile_employer': User.objects.get(pk=employer.user_id)
        }
        return render(request, 'requests/employer_request.html', context)
    except:
        print('err')
        return render(request, 'requests/employer_request.html')


@login_required
def update_employer_request(request, id):
    user = request.user
    employee = Employee.objects.get(user_id=user.id)
    leave_request = LeaveRequest.objects.get(pk=id)
    form = LeaveRequestForm(request.POST or None)
    id_user = str(employee.id)
    # employer
    employer = Employee.objects.get(pk=leave_request.employee_id)
    if request.method == 'POST' and 'refuse' in request.POST:
        accept_refuse(leave_request.id, 'rejected')
        return redirect('/leave/employers_requests/' + id_user)
    if request.method == 'POST' and 'accept' in request.POST:
        accept_refuse(leave_request.id, 'accepted')
        return redirect('/leave/employers_requests/' + id_user)
    context = {
        'employer': employer,
        'leave_request': leave_request,
        'profile_employer': User.objects.get(pk=employer.user_id)
    }
    return render(request, 'requests/employer_request.html', context)


@login_required
def delete_employer_request(request, id):
    user = request.user
    employee = Employee.objects.get(user_id=user.id)
    if employee.tag_manager is True:
        leave_request = LeaveRequest.objects.get(pk=id)
        leave_request.delete()
        id_user = str(employee.id)
        return redirect('/leave/employers_requests/' + id_user)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def employers_requests(request, id):
    user = request.user
    employee = Employee.objects.get(user_id=user.id)
    if employee.tag_manager is True:
        requests_list = LeaveRequest.objects.filter(manager_id=id)
        context = {
            'requests_list': requests_list
        }
        return render(request, 'requests/employers_requests.html', context)
    else:
        return render(request, 'users/forbideen.html')

akTeams/templates/LeaveRequest/formLeaverequest.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <ol class="breadcrumb ">
        <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> Home</a></li>
          <li class="active"> Leave Request </li>

      </ol>

 <form method="POST" >
        <div class="box box-info">
            <div class="box-header">


  <h3 class="box-title">New Leave request</h3>





            </div>
            <div class="box-body">

<form method="POST" >

                            {% csrf_token %}
    <div class="form-group">


    <div class="custom-control row">
        <div class="col-md-2">
         <select class="pull-left form-control" name="partieJour" id="partieJour">
                    <option value="AM">Matinée</option>
                    <option value="PM">après-midi</option>
                  </select>
            </div>
        <div class="col-md-9">
        <div class="pull-right" >
        <label class="switch">
      <input type="checkbox" name="isJournee"  id="switchJounrnee" value="Yes" checked>
         <span class="slider round"></span>

            </label>
        <label for="switchJounrnee" >Journée Entière</label>
            </div>
            </div>
{#      <label class="custom-control-label" for="switchJounrnee">Journée Entière</label>#}
    </div>
<br>
  </div>


              <div class="form-group">
                <label for="id_start_date">Date Debut:</label>

                <div class="input-group date">
                  <div class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                  </div>
                  <input type="text" name="start_date" class="form-control pull-right datepicker"  id="id_start_date" >
                </div>
                <!-- /.input group -->
              </div>

             {% comment %} <div class="bootstrap-timepicker form-group">
                <div class="form-group">
                  <label for="id_debutHeure">Heure Debut:</label>

                  <div class="input-group">
                                          <div class="input-group-addon">
                      <i class="fa fa-clock-o"></i>
                    </div>
                    <input type="text" name="debutHeure" id="id_debutHeure" class="form-control timepicker">


                  </div>
                  <!-- /.input group -->
                </div>
                <!-- /.form group -->
              </div>{% endcomment %}
              <div class="form-group" id="dateFin">
                <label for="id_end_date">Date Fin:</label>

                <div class="input-group date">
                  <div class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                  </div>
                  <input type="text" name="end_date" class="form-control pull-right datepicker"  id="id_end_date" >
                </div>
                <!-- /.input group -->
              </div>

            {% comment %}  <div class="bootstrap-timepicker form-group">
                <div class="form-group">
                  <label for="id_finHeure">Heure Fin:</label>

                  <div class="input-group">
                                          <div class="input-group-addon">
                      <i class="fa fa-clock-o"></i>
                    </div>
                    <input type="text" name="finHeure" id="id_finHeure" class="form-control timepicker">


                  </div>
                  <!-- /.input group -->
                </div>
                <!-- /.form group -->
              </div>{% endcomment %}


            <div class="form-group">

              <label for="{{ form.leave_type.id_for_label }}" >{{ form.leave_type.label }}</label>

              {{ form.leave_type }}


            </div>
            <div class="form-group">

              <label for="{{ form.reason.id_for_label }}" >{{ form.reason.label }}</label>

              {{ form.reason }}


            </div>


            </div>






            <div class="box-footer clearfix">
                <div class="pull-right">


                    <button type="submit" name="creedemande" class="btn bg-olive margin ">
                    Envoyer la demande</button>
                </div>



</form>
            </div>
          </div>

    </form>









        <script type="text/javascript">

           $(function () {

               if($('#switchJounrnee').is(':checked'))
               {
                   $('#partieJour').hide();
                   $('#dateFin').show();
               }

               $('#switchJounrnee').click(function () {
                   if(this.checked) {

               $('#partieJour').hide();
               $('#dateFin').show();

                }
                else {

                    $('#partieJour').show();
                    $('#dateFin').hide();
                   }

               })
    //Initialize Select2 Elements
    $('.select2').select2()

    //Datemask dd/mm/yyyy
    $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })

    $('[data-mask]').inputmask()


    //Date picker

    $('.datepicker').datepicker({

        format: 'yyyy-mm-dd',
      autoclose: true,
       startDate: '0d',
    }).datepicker("setDate",'now');

    //Timepicker
    $('.timepicker').timepicker({
     showMeridian: false,
    })
  })
        </script>

{% endblock %}

akTeams/templates/LeaveRequest/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



      <ol class="breadcrumb ">
        <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> Home</a></li>
          <li ><a href="{% url 'leaveRqt.index' %}"> Leave Request </a></li>
        <li class="active"> My Leave</li>
      </ol>


     <div class="box box-info">
            <div class="box-header">

  <h3 class="box-title">Leave request</h3>
            </div>

            <div class="box-body table-responsive no-padding">
              <table class="table table-hover table-earning">
                    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">start_date</th>
      <th scope="col">end_date</th>
        <th scope="col">debutHeure</th>
        <th scope="col">finHeure</th>
        <th scope="col">create_date</th>
        <th scope="col">status</th>
{#      <th scope="col">action</th>#}
    </tr>

                   <tbody>

                                {% for item in list_reqLeave %}

                                    <tr>

                                        <td> {{ item.id }}</td>

                                        <td> {{ item.start_date}}</td>
                                        <td> {{ item.end_date}}</td>
                                        <td> {{ item.debutHeure}}</td>
                                        <td> {{ item.finHeure}}</td>
                                        <td> {{ item.create_date}}</td>
                                        <td>
                                             {% if item.status == 'Waiting' %}

                                                  <span class="badge badge-info" style="color:white; background-color: #00c0ef">
                                                      <a style="color:white; background-color: #00c0ef" href="{% url 'leaveRqt.showMyleave'  item.id%}">
                                                          {{ item.status}}
                                                      </a></span>

                                             {% endif %}

                                             {% if item.status == 'Rejected' %}

                                                  <span class="badge badge-danger" style="background-color: #f56954">{{ item.status}}</span>

                                             {% endif %}
                                            {% if item.status == 'Accepted' %}

                                                  <span class="badge badge-success" style="background-color: #00a65a">{{ item.status}}</span>

                                             {% endif %}
                                            {% if item.status == 'Canceled' %}

                                                  <span class="badge badge-warning" style="background-color: #f39c12">{{ item.status}}</span>

                                             {% endif %}
                                            </td>

{#                                    <td style="width: 40px">#}
{##}
{#                                        <a  style="color: red" href="{% url 'leaveType.delete' item.id %}">#}
{#                                             <i class="fa fa-"></i>#}
{#                                         </a>#}
{##}
{##}
{#                                    </td>#}
                                    </tr>

                                {% endfor %}

                            </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>



{% endblock %}

akTeams/templates/LeaveRequest/login.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Leave Management</title>


    <link rel="stylesheet" type="text/css" href="{% static 'team/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'team/AdminLTE.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'team/_all-skins.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'team/bootstrap-datepicker.css' %}">

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
<script src="{% static 'js/adminlte.min.js' %}"></script>
<script src="{% static 'js/pages/dashboard.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

</head>

<body >

<form method="POST" >
        <div class="box box-info">
            <div class="box-header">


  <h3 class="box-title">Login</h3>





            </div>
            <div class="box-body" >




                            {% csrf_token %}

                           {% for field in form %}
<div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
    <div class="col-sm-4">
      {{ field }}
    </div>

  </div>


        {% endfor %}

            </div>

            <div class="box-footer clearfix">



                    <button type="submit" class="btn bg-olive">
                    Login</button>



            </div>
          </div>

    </form>




</body>

</html>

akTeams/templates/LeaveRequest/myleave.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

      <ol class="breadcrumb ">
        <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li ><a href="{% url 'leaveRqt.index' %}"> Leave Request </a></li>
          <li class="active"> My Leave </li>

      </ol>

    <form method="POST" >
{% csrf_token %}


    <div class="row">

     <div class="col-md-12">
            <div class="box-header">


  <h3 class="box-title">My Leave request</h3>





            </div>
         <div class="box box-primary ">
            <div class="box-body  ">

                <div class="container" >
  <div class="row">
    <div class="col-md-6">
     <label>Date debut :</label>
        {{ item.start_date|date:"d-m-y" }}
    </div>
    <div class="col-md-6">
     <label>Heure debut :</label>
        {{ item.debutHeure|time:"H:i " }}
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
     <label>Date Fin :</label>
        {{ item.end_date|date:"d-m-y" }}
    </div>
    <div class="col-md-6">
     <label>Heure Fin :</label>
        {{ item.finHeure|time:"H:i " }}
    </div>
  </div>
                      <div class="row">
     <label class="col-md-6 form-group">Motifs :</label>
<p class="col-md-6 ">
           {{ item.leave_type}}
      </p>

  </div>
  <div class="row">
     <label class="col-md-6 form-group">Note :</label>
<p class="col-md-6 ">
           {{ item.reason}}
      </p>

  </div>
</div>

            </div>

              <div class="box-footer">
                  <div class="pull-right">
                       {% if item.status == 'Waiting' %}
                       <button type="submit"  class="btn bg-maroon margin " name="anuuler">
                    Annuler</button>
                       {% endif %}
                  </div>
  </div>
          </div>
     </div>


</form>

</div>

{% endblock %}

akTeams/templates/LeaveRequest/show.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

      <ol class="breadcrumb ">
        <li><a href="{% url 'dashboard' %}"><i class="fa fa-dashboard"></i> Home</a></li>
          <li class="active"> Leave Request </li>

      </ol>

    <form method="POST" >
{% csrf_token %}


    <div class="row">
        <div class="col-md-3">
            <div class="box box-primary ">
            <div class="box-body box-profile">

              <img src="{% static 'img/user2-160x160.jpg' %}" class="profile-user-img img-responsive img-circle" alt="User Image">
              <h3 class="profile-username text-center">{{ item.employee }}</h3>

              <p class="text-muted text-center">{{ item.employee.be }}</p>
              <p class="text-muted text-center">{{ item.employee.positon }}</p>

            </div>
            <!-- /.box-body -->
          </div>
        </div>
     <div class="col-md-9">

         <div class="box box-primary ">
            <div class="box-body  ">

                <div class="container" style="height: 200px">
  <div class="row">
    <div class="col-md-6">
     <label>Date debut :</label>
        {{ item.start_date|date:"d-m-y" }}
    </div>
    <div class="col-md-6">
     <label>Heure debut :</label>
        {{ item.debutHeure|time:"H:i " }}
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
     <label>Date Fin :</label>
        {{ item.end_date|date:"d-m-y" }}
    </div>
    <div class="col-md-6">
     <label>Heure Fin :</label>
        {{ item.finHeure|time:"H:i " }}
    </div>
  </div>
                      <div class="row">
     <label class="col-md-6 form-group">Motifs :</label>
<p class="col-md-6 ">
           {{ item.leave_type}}
      </p>

  </div>
  <div class="row">
     <label class="col-md-6 form-group">Note :</label>
<p class="col-md-6 ">
           {{ item.reason}}
      </p>

  </div>
</div>

            </div>

              <div class="box-footer">
                  <div class="pull-right">
                       <button type="submit"  class="btn bg-maroon margin " name="Rejected">
                    Refuser</button>
     <button  class="btn bg-olive margin " type="submit"  name="Accepted">
                    Accepter</button>
                  </div>
  </div>
          </div>
     </div>


</form>

</div>

{% endblock %}