employee_leave_management/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('leave/', include('leaveManagmentItazouti.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('register/<id>', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name= 'users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('change_password/', user_views.change_password, name='change_password'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settingEmployer/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'CRUD'
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<id>', views.delete, name='delete'),
    path('edit/<id>', views.edit, name='edit'),
    path('teams', views.teams, name='teams'),
    path('delete_team/<id>', views.delete_team, name='delete_team'),
    path('register/<id>', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('add_teams', views.add_teams, name='add_teams'),
    path('find_team/<id>', views.find_team, name='find_team'),
    path('edit_team/<id>', views.edit_team, name='edit_team'),
    path('bu', views.bu, name='bu'),
    path('add_bu', views.add_bu, name='add_bu'),
    path('edit_bu/<id>', views.edit_bu, name='edit_bu'),
    path('find_bu/<id>', views.find_bu, name='find_bu'),
    path('delete_bu/<id>', views.delete_bu, name='delete_bu'),
    path('position', views.position, name='position'),
    path('add_position', views.add_position, name='add_position'),
    path('edit_position/<id>', views.edit_position, name='edit_position'),
    path('find_position/<id>', views.find_position, name='find_position'),
    path('delete_position/<id>', views.delete_position, name='delete_position'),
    path('add_newEmployer', views.add_newEmployer, name='add_newEmployer'),
    path('notification', views.notification, name='notifications.css'),
]

yh_be/urls.py
from django.urls import path
from . import views

# map urls with views
urlpatterns = [
    path('', views.index, name='be.index'),
    path('<int:id>', views.show, name='be.show'),
    path('create', views.create, name='be.create'),
    path('update/<int:id>', views.update, name='be.update'),
    path('delete/<int:id>', views.delete, name='be.delete'),
]

settingEmployer/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
from employee_leave_management import settings


class BusinessUnit(models.Model):
    be_Code = models.CharField(max_length=10, null=True, blank=True, unique=True)
    libelle = models.CharField(max_length=100)

    def __str__(self):
        return self.libelle


class Position(models.Model):
    position_code = models.CharField(max_length=10, null=True, blank=True, unique=True)
    libelle = models.CharField(max_length=200)

    def __str__(self):  # __unicode__ on Python 2
        return self.libelle


class Team(models.Model):
    team_code = models.CharField(max_length=10, null=True, blank=True, unique=True)
    libelle = models.CharField(max_length=200)

    def __str__(self):
        return self.libelle


class Employee(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    cin_code = models.CharField(max_length=10, unique=True, null=True)
    birth_date = models.DateField(null=True)
    hire_date = models.DateField(null=True)
    email = models.EmailField(max_length=100, blank=False, unique=True, null=True)
    cnss_code = models.CharField(max_length=30, unique=True, null=True)
    experience_years_number = models.IntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now, blank=True)
    leave_days_number = models.FloatField(null=True, blank=True)
    resignation_date = models.DateField(null=True, blank=True)
    be = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE, null=True)
    positon = models.ForeignKey(Position, on_delete=models.CASCADE, null=True)
    manager = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    tag_manager = models.BooleanField(default=False)
    team = models.ManyToManyField(Team)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.first_name



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

settingEmployer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Employee, Team, BusinessUnit, Position
from .forms import EditForm, TeamForm, BUForm, PositionForm, EmployerCreate
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required


def get_user_employer(request):
    user = request.user
    try:
        employer_user = Employee.objects.get(user_id=user.id)
        context = {
            'employer_user': employer_user,
            'exit': True
        }
    except:
        context = {
            'exit': False
        }
    return context


def notification(request):
    return render(request, 'users/notifications.css.html')


@login_required
def index(request):
    user = request.user
    try:
        employer = Employee.objects.get(user_id=user.id)
        if user.is_superuser is True:
            context = {
                'employers': Employee.objects.all(),
                'employer': employer,
            }
            return render(request, 'employers/employerList.html', context)
        else:
            return redirect('/leave/requestList')
    except:
        return render(request, 'employers/not_found.html')


@login_required
def add_newEmployer(request):
    user = request.user
    if user.is_superuser is True:
        form = EmployerCreate(request.POST or None)
        if form.is_valid():
            employer = form.save(commit=False)
            employer.save()
            id_employer = str(employer.id)
            return redirect('/setting/register/' + id_employer)
        else:
            print(form.errors)
        return render(request, 'employers/createUser.html', {'form': form})
    else:
        return render(request, 'users/forbideen.html')


@login_required
def register(request, id):
    user = request.user
    employer = Employee.objects.get(user_id=user.id)
    if user.is_superuser is True:
        if request.method == 'POST':
            form = UserRegisterForm(request.POST or None)
            if form.is_valid():
                employee = get_object_or_404(Employee, pk=id)
                employer_user = form.save(commit=False)
                employer_user.email = employee.email
                employer_user.first_name = employer.first_name
                employer_user.last_name = employer.last_name
                employer_user.save()
                employee.user = employer_user
                employee.save()
                return redirect('/setting/')
        else:
            form = UserRegisterForm()
        return render(request, 'users/register.html', {'form': form})
    else:
        return render(request, 'users/forbideen.html')


# delete function
@login_required
def delete(request, id):
    user = request.user
    if user.is_superuser is True:
        employer = Employee.objects.get(pk=id)
        employer.delete()
        return redirect('/setting')
    else:
        return render(request, 'users/forbideen.html')


@login_required
def edit(request, id):
    user = request.user
    if user.is_superuser is True:
        employee = get_object_or_404(Employee, pk=id)
        form = EditForm(request.POST or None, instance=employee)
        if form.is_valid():
            form.save()
            messages.info(request, 'You have updated  this element successfully.')
        context = {
            'form': form,
            'employee': employee
        }
        return render(request, 'employers/edit.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def teams(request):
    user = request.user
    if user.is_superuser is True:
        allTeams = Team.objects.all()
        form_team = TeamForm()
        context = {
            'teams': allTeams,
            'form_team': form_team
        }
        return render(request, 'teams/teamsList.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def delete_team(request, id):
    user = request.user
    if user.is_superuser is True:
        team = Team.objects.get(pk=id)
        team.delete()
        messages.info(request, 'You have deleted this element successfully.')
        return redirect('/setting/teams')
    else:
        return render(request, 'users/forbideen.html')


@login_required
def add_teams(request):
    user = request.user
    if user.is_superuser is True:
        if request.method == "POST":
            form = TeamForm(request.POST)
            if form.is_valid():
                form.save()
        messages.info(request, 'You have added new element successfully.')
        return redirect('/setting/teams')
    else:
        return render(request, 'users/forbideen.html')


@login_required
def find_team(request, id):
    user = request.user
    if user.is_superuser is True:
        team = Team.objects.get(pk=id)
        context = {
            'teamf': team
        }
        return render(request, 'teams/delete_team.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def edit_team(request, id):
    user = request.user
    if user.is_superuser is True:
        team = get_object_or_404(Team, pk=id)
        form = TeamForm(request.POST or None, instance=team)
        if form.is_valid():
            form.save()

        context = {
            'form_edit': form,
            'team': team
        }
        messages.info(request, 'You have updated this element successfully.')
        return render(request, 'teams/edit_team.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def bu(request):
    user = request.user
    if user.is_superuser is True:
        all_bu = BusinessUnit.objects.all()
        form_add = BUForm()
        context = {
            'buList': all_bu,
            'form': form_add
        }
        return render(request, 'bu/buList.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def add_bu(request):
    user = request.user
    if user.is_superuser is True:
        if request.method == "POST":
            form = BUForm(request.POST)
            if form.is_valid():
                form.save()
        messages.info(request, 'You have added new element successfully.')
        return redirect('/setting/bu')
    else:
        return render(request, 'users/forbideen.html')


@login_required
def edit_bu(request, id):
    user = request.user
    if user.is_superuser is True:
        bu = get_object_or_404(BusinessUnit, pk=id)
        form = BUForm(request.POST or None, instance=bu)
        if form.is_valid():
            form.save()

        context = {
            'form_edit': form,
            'bu': bu
        }
        messages.info(request, 'You have updated this element successfully.')
        return render(request, 'bu/edit_bu.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def find_bu(request, id):
    user = request.user
    if user.is_superuser is True:
        bu = BusinessUnit.objects.get(pk=id)
        context = {
            'bu': bu
        }
        return render(request, 'bu/delete.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def delete_bu(request, id):
    user = request.user
    if user.is_superuser is True:
        bu = BusinessUnit.objects.get(pk=id)
        bu.delete()
        messages.info(request, 'You have deleted this element successfully.')
        return redirect('/setting/bu')
    else:
        return render(request, 'users/forbideen.html')


@login_required
def position(request):
    user = request.user
    if user.is_superuser is True:
        all_position = Position.objects.all()
        form_add = PositionForm()
        context = {
            'positions': all_position,
            'form': form_add
        }
        return render(request, 'position/positionsList.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def add_position(request):
    user = request.user
    if user.is_superuser is True:
        user = request.user
        if user.is_superuser is True:
            if request.method == "POST":
                form = PositionForm(request.POST)
                if form.is_valid():
                    form.save()
            messages.info(request, 'You have added new element successfully.')
            return redirect('/setting/position')

    else:
        return render(request, 'users/forbideen.html')


@login_required
def edit_position(request, id):
    user = request.user
    if user.is_superuser is True:
        p = get_object_or_404(Position, pk=id)
        form = PositionForm(request.POST or None, instance=p)
        if form.is_valid():
            form.save()
            messages.info(request, 'You have updated this element successfully.')
            return redirect('/setting/position')
        context = {
            'form_edit': form,
            'position': position
        }

        return render(request, 'position/edit_position.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def find_position(request, id):
    user = request.user
    if user.is_superuser is True:
        p = Position.objects.get(pk=id)
        context = {
            'position': p
        }
        return render(request, 'position/delete.html', context)
    else:
        return render(request, 'users/forbideen.html')


@login_required
def delete_position(request, id):
    user = request.user
    if user.is_superuser is True:
        p = Position.objects.get(pk=id)
        p.delete()
        messages.info(request, 'You have deleted this element successfully.')
        return redirect('/setting/position')
    else:
        return render(request, 'users/forbideen.html')


@login_required
def profile(request):

settingEmployer/templates/bu/buList.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="app-title">
    <div>
        <h1><i class="fa fa-group"></i> Add new Business unit </h1>
        <p>Add new BU to the list</p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
               {% if messages %}

            <ul class="messages">
                <div class="alert alert-success alert-dismissible">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </div>
            </ul>
            {% endif %}

                        <a type="button" class="btn btn-primary btn-sm"
                           style="font-size: 16px;color: white;background: #45637f;" data-toggle="modal"
                           data-target="#add"><i
                                class="fa fa-plus-circle"></i>
                            &nbsp;&nbsp;Add New BU</a><br><br>
                        <!-- Modal Delete -->
                        <div class="modal fade" id="add" tabindex="-1" role="dialog"
                             aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header" style="text-align: center;">
                                        <center><strong><span style="font-family: Poppins-SemiBold;color:black">Add new BU to the list</span>
                                        </strong></center>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body" style="color:black;font-size:17px">
                                        <form method="POST" action="/setting/add_bu">
                                            {% csrf_token%}
                                            <span style="margin-left: -79%;font-family: Poppins-SemiBold;"> Name:</span><br>
                                            {{form.libelle}}

                                            <br>
                                            <button type="submit" class="btn btn-success"
                                                    style="font-size: 16px;color: white;margin-left: 44%;">
                                                <i class="fa fa-plus-circle"></i> Add new BU
                                            </button>
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                            </button>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>


                </div>
                <center>
                    <table class="table table-hover" id="sampleTable"
                           style="font-family: Poppins-SemiBold;font-size: 15px;width:60%;">
                        <thead style="text-align: center;">
                        <tr>
                            <th>Id</th>
                            <th>Label</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for bu in buList %}
                        <tr style="text-align: center;">
                            <td>{{bu.id}}</td>
                            <td style="width:70%;">{{bu.libelle}}</td>
                            <td>
                                <a class="btn btn-danger" href="{% url 'CRUD:edit_bu' bu.id %}" style="background: transparent;color: #45637f;
                               border: none;"><i class="fa fa-edit" style="font-size: 19px;"></i></a>
                                <a class="btn btn-danger" href="{% url 'CRUD:find_bu' bu.id %}" style="background: transparent;color: #e73737;
                               border: none;"><i class="fa fa-trash-o" style="font-size: 19px;"></i></a>
                            </td>
                        </tr>
                        {% endfor%}
                        </tbody>
                    </table>
                </center>
            </div>
        </div>
    </div>
</div>

{% endblock %}

settingEmployer/templates/bu/delete.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="app-title">
    <div>
        <h4><i class="fa  fa-question-circle"></i> Are you sure?</h4>
        <p>Are you sure you want to delete the business unit "{{teamf.libelle}}"??</p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <span class="label-input100" style="margin-left: 35%;"><strong> Team Id:</strong></span>
                            <input class="input100" type="text" value="{{bu.id}}" disabled style="width: 50%;
                            margin-left: 20%;margin-top: 1%;"/>
                            <br>
                            <span class="label-input100" style="margin-left: 35%;"><strong> Team Name:</strong></span>
                            <input class="input100" type="text" value="{{bu.libelle}}" disabled style="width: 50%;
                            margin-left: 20%;margin-top: 1%;"/>
                            <br><br>
                            <a class="btn btn-danger" href="{% url 'CRUD:delete_bu' bu.id %}" style="
                               border: none;"><i class="fa fa-trash-o" style="font-size: 16px;"></i>&nbsp;&nbsp;Delete</a>
                            <a class="btn btn-secondary" href="{% url 'CRUD:bu' %}"
                               style="border: none;"><i class="fa  fa-arrow-left" style="font-size: 16px;"></i>&nbsp;&nbsp;No,Back to the list </a>
                        </div>
                        <div class="col">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

settingEmployer/templates/bu/edit_bu.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="app-title">
    <div>
        <h1><i class="fa fa-edit"></i> Update Business unit Information</h1>
        <p>In this page you will find all information about "{{ bu.libelle }}" BU </p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="tile">
            <div class="tile-body">
                <div class="small_div">
                    <div class="container">
                        <form class="contact100-form" action="" method="POST">
                            {% csrf_token%}
                            <div class="row justify-content-md-center">
                                <div class="col col-lg-1">
                                    <span class="label-input100"
                                          style="margin-left: 35%;"><strong> BU Id:</strong></span><br><br>
                                    <span class="label-input100"
                                          style="margin-left: 35%;"><strong> BU Name:</strong></span>
                                </div>
                                <div class="col-md-auto" style="margin-left: -10%;">
                                    {{bu.id}}<br><br>
                                    {{form_edit.libelle}}<br>
                                    <input class="btn btn-outline-warning" type="submit" value="Update">
                                    <a class="btn btn-outline-secondary" href="{% url 'CRUD:bu' %}"
                               style="border: none;"><i class="fa  fa-arrow-left" style="font-size: 16px;"></i>&nbsp;&nbsp;No,Back to the list </a>

                                </div>
                                <div class="col col-lg-4">

                                </div>
                                <div>
                                </div>
                            </div>


                          <br><br>

                        </form>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
</div>
</div>


{% endblock %}